# Generated by Django 3.2.6 on 2021-08-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='CarCategory',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.carcategory'),
            preserve_default=False,
        ),
    ]
