# Generated by Django 3.2.6 on 2021-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210818_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name_plural': 'Car Categories'},
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
