# Generated by Django 3.2.6 on 2021-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
